name: My Mini Project

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Demo
      run: echo "Hello World"

  docker_image:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_UNAME}}
          password: ${{DOCKER_PASS}}

      - name: Build docker image
        run: docker build -t docker-flask-app .
      
