name: My Mini Project

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Demo
      run: echo "Hello World"

  docker_image:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_UNAME}}
          password: ${{secrets.DOCKER_PASS}}

      - name: Build docker image
        run: docker build -t ${{ secrets.DOCKER_UNAME }}/flask-docker-app:latest .

      - name: Push to docker hub
        run: docker push ${{ secrets.DOCKER_UNAME }}/flask-docker-app:latest

  ssh-ec2:
    runs-on: ubuntu-latest
    needs: docker_image
    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{secrets.EC2_SSH_KEY}}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: pull docker image
        run: ssh -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "docker pull ${{secrets.DOCKER_UNAME}}/flask-docker-app:latest && docker stop flask-app || true && docker rm flask-app || true && docker run -d -p 5000:5000 --name flask-app ${{secrets.DOCKER_UNAME}}/flask-docker-app:latest"


      
